name: Start TN Server

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: STNSIDB
      run: ./init-db -data=data.json
    - name: STNSSS
      run: ./tinode
